// src/app/layout.js (atau layout.tsx)

import { Inter } from 'next/font/google'
import './globals.css'

// Sesuaikan ini dengan setup font Anda di config
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* TAMBAHKAN KELAS TAILWIND DI SINI! 
        Kita gunakan nama dari tailwind.config.js Anda:
        'bg-neutral-50' (atau 'bg-muted' jika Anda pakai nama baru)
        'text-neutral-800' (atau 'text-base-text')
      */}
      <body className={`${inter.className} bg-neutral-50 text-neutral-800`}>
        {children}
      </body>
    </html>
  )
}